runtime: python39  # Use the appropriate Python version
env: standard

instance_class: F2  # Increase instance class to handle more memory

handlers:
  - url: /.*
    script: auto

readiness_check:
  path: "/readines_check"
  app_start_timeout_sec: 1800