runtime: python310  # Use the appropriate Python version
env: standard

entrypoint: gunicorn -b :$PORT -w 1 main:app

handlers:
  - url: /.*
    script: auto

readiness_check:
  path: "/readines_check"
  app_start_timeout_sec: 1800